name: docker build

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set COMMIT_SHA_SHORT
        run: echo "::set-env name=COMMIT_SHA_SHORT::$(git rev-parse --short HEAD)"

      - uses: actions/setup-java@v1
        with:
          java-version: 13

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: ./gradlew jib -Djib.to.tags=latest,${COMMIT_SHA_SHORT}
